package questionRules
import java.util.ArrayList
import com.sbnz.model.Color
import com.sbnz.model.Structure
import com.sbnz.model.Experiment
import com.sbnz.model.Substance
import com.sbnz.model.ResponseDTO
import com.sbnz.model.Cation
import com.sbnz.model.Anion
import com.sbnz.model.PreviousQuestion

rule "First Question"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 0);
    then
        System.out.println("First Question");
        $s.setQuestionId(1);
    end

rule "Question 1 Answer 1"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 1, answerId == 1);
    then
        $s.setQuestionId(7);
    end
rule "Question 1 Answer 2"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 1, answerId == 2);
    then
        $s.setQuestionId(2);
    end
rule "Question 1 Answer 3"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 1, answerId == 3);
    then
        $s.setQuestionId(7);
    end
rule "Question 1 Answer 4"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 1, answerId == 4);
    then
        $s.setQuestionId(2);
    end
rule "Question 2 Answer 1"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 2, answerId == 1);
    then
        $s.setQuestionId(7);
    end
rule "Question 2 Answer 2"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 2, answerId == 2);
    then
        $s.setQuestionId(3);
    end
rule "Question 2 Answer 3"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 2, answerId == 3);
    then
        $s.setQuestionId(3);
    end
rule "Question 3 Answer 1"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 3, answerId == 1);
    then
        $s.setQuestionId(5);
    end
rule "Question 3 Answer 2"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 3, answerId == 2);
    then
        $s.setQuestionId(4);
    end
rule "Question 3 Answer 3"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 3, answerId == 3);
    then
        $s.setQuestionId(5);
    end
rule "Question 4 Answer 1"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 4, answerId == 1);
    then
        $s.setQuestionId(7);
    end
rule "Question 4 Answer 2"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 4, answerId == 2);
    then
        $s.setQuestionId(14);
    end
rule "Question 4 Answer 3"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 4, answerId == 3);
    then
        $s.setQuestionId(7);
    end
rule "Question 5 Answer 1"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 5, answerId == 1);
    then
        $s.setQuestionId(6);
    end
rule "Question 5 Answer 2"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 5, answerId == 2);
    then
        $s.setQuestionId(7);
    end
rule "Question 5 Answer 3"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 5, answerId == 3);
    then
        $s.setQuestionId(14);
    end
rule "Question 5 Answer 4"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 5, answerId == 4);
    then
        $s.setQuestionId(6);
    end
rule "Question 6 Answer 1"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 6, answerId == 1);
    then
        $s.setQuestionId(7);
    end
rule "Question 6 Answer 2"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 6, answerId == 2);
    then
        $s.setQuestionId(14);
    end
rule "Question 6 Answer 3"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 6, answerId == 3);
    then
        $s.setQuestionId(7);
    end
rule "Question 7 Answer 1"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 7, answerId == 1);
    then
        $s.setQuestionId(8);
    end
rule "Question 7 Answer 2"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 7, answerId == 2);
    then
        $s.setQuestionId(9);
    end
rule "Question 7 Answer 3"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 7, answerId == 3);
    then
        $s.setQuestionId(9);
    end
rule "Question 8 Answer 1"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 8, answerId == 1);
    then
        $s.setQuestionId(14);
    end
rule "Question 8 Answer 2"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 8, answerId == 2);
    then
        $s.setQuestionId(14);
    end
rule "Question 8 Answer 3"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 8, answerId == 3);
    then
        $s.setQuestionId(14);
    end
rule "Question 8 Answer 4"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 8, answerId == 4);
    then
        $s.setQuestionId(9);
    end
rule "Question 9 Answer 1"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 9, answerId == 1);
    then
        $s.setQuestionId(11);
    end
rule "Question 9 Answer 2"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 9, answerId == 2);
    then
        $s.setQuestionId(10);
    end
rule "Question 9 Answer 3"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 9, answerId == 3);
    then
        $s.setQuestionId(11);
    end
rule "Question 10 Answer 1"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 10, answerId == 1);
    then
        $s.setQuestionId(14);
    end
rule "Question 10 Answer 2"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 10, answerId == 2);
    then
        $s.setQuestionId(14);
    end
rule "Question 10 Answer 3"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 10, answerId == 3);
    then
        $s.setQuestionId(11);
    end
rule "Question 11 Answer 1"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 11, answerId == 1);
    then
        $s.setQuestionId(14);
    end
rule "Question 11 Answer 2"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 11, answerId == 2);
    then
        $s.setQuestionId(12);
    end
rule "Question 11 Answer 3"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 11, answerId == 3);
    then
        $s.setQuestionId(14);
    end
rule "Question 12 Answer 1"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 12, answerId == 1);
    then
        $s.setQuestionId(13);
    end
rule "Question 12 Answer 2"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 12, answerId == 2);
    then
        $s.setQuestionId(14);
    end
rule "Question 12 Answer 3"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 12, answerId == 3);
    then
        $s.setQuestionId(14);
    end
rule "Question 13 Answer 1"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 13, answerId == 1);
    then
        $s.setQuestionId(14);
    end
rule "Question 13 Answer 2"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 13, answerId == 2);
    then
        $s.setQuestionId(14);
    end
rule "Question 13 Answer 3"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 13, answerId == 3);
    then
        $s.setQuestionId(14);
    end
rule "Question 14 Answer 1"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 14, answerId == 1);
    then
        $s.setQuestionId(15);
    end
rule "Question 14 Answer 2"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 14, answerId == 2);
    then
        $s.setQuestionId(0);
    end
rule "Question 14 Answer 3"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 14, answerId == 3);
    then
        $s.setQuestionId(15);
    end
rule "Question 15 Answer 1"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 15, answerId == 1);
    then
        $s.setQuestionId(16);
    end
rule "Question 15 Answer 2"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 15, answerId == 2);
    then
        $s.setQuestionId(0);
    end
rule "Question 15 Answer 3"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 15, answerId == 3);
    then
        $s.setQuestionId(16);
    end
rule "Question 16 Answer 1"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 16, answerId == 1);
    then
        $s.setQuestionId(17);
    end
rule "Question 16 Answer 2"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 16, answerId == 2);
    then
        $s.setQuestionId(0);
    end
rule "Question 16 Answer 3"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 16, answerId == 3);
    then
        $s.setQuestionId(17);
    end
rule "Question 17 Answer 1"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 17, answerId == 1);
    then
        $s.setQuestionId(18);
    end
rule "Question 17 Answer 2"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 17, answerId == 2);
    then
        $s.setQuestionId(0);
    end
rule "Question 17 Answer 3"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 17, answerId == 3);
    then
        $s.setQuestionId(18);
    end
rule "Question 18 Answer 1"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 18, answerId == 1);
    then
        $s.setQuestionId(19);
    end
rule "Question 18 Answer 2"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 18, answerId == 2);
    then
        $s.setQuestionId(0);
    end
rule "Question 18 Answer 3"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 18, answerId == 3);
    then
        $s.setQuestionId(19);
    end
rule "Question 19 Answer 1"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 19, answerId == 1);
    then
        $s.setQuestionId(20);
    end
rule "Question 19 Answer 2"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 19, answerId == 2);
    then
        $s.setQuestionId(0);
    end
rule "Question 19 Answer 3"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 19, answerId == 3);
    then
        $s.setQuestionId(20);
    end
rule "Question 20 Answer 1"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 20, answerId == 1);
    then
        $s.setQuestionId(0);
    end
rule "Question 20 Answer 2"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 20, answerId == 2);
    then
        $s.setQuestionId(0);
    end
rule "Question 20 Answer 3"
    when
        $s : ResponseDTO();
        $previousQuestion : PreviousQuestion(questionId == 20, answerId == 3);
    then
        $s.setQuestionId(0);
    end